### ISSUE TITLE
with ionic framework

### ISSUE THREAD

**Issue by leribol** [j3k0/cordova-plugin-openwith#1]
The plugin worked in ionic - android without any problem. 
In ionic - ios, it worked  but the receiver app (my app) could not get the data.
What could we do.

**Comment by j3k0** [comment]
> In ionic - ios, it worked but the receiver app (my app) could not get the data.

Does the sharing dialog open the app? (to check if the custom url scheme is well defined when using ionic)

If it does, it means the data has been added to a shared user-preferences. If you can open the Xcode project on iOS, you can make sure both the Share extension and App are in the same App Group (see README about that)
