### ISSUE TITLE
New release 2.1.0?

### ISSUE THREAD

**Issue by NiklasMerz** [j3k0/cordova-plugin-openwith#116]
@j3k0 Should we do a new NPM release with the latest improvements? I could do it if I find time in the next days?

**Comment by Saqib92** [comment]
Waiting for the updates.

**Comment by NiklasMerz** [comment]
It took a long time but I just released a new version https://github.com/j3k0/cordova-plugin-openwith/releases/tag/v2.1.0

**Comment by Saqib92** [comment]
will it support Capacitor?

**Comment by NiklasMerz** [comment]
You can test this yourself, but probably not out of the box as this
plugins uses hooks which are not supported by capacitor. You might need
to adjust files in your Xcode project.

On November 10, 2021, GitHub ***@***.***> wrote:
> will it support Capacitor?
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/j3k0/cordova-plugin-
openwith/issues/116#issuecomment-964836578>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AA3LORHJE33YRAX7BIS62ETULIJLZANCNFSM474OLBHQ>.
