### ISSUE TITLE
Info.plist issue and 'ShareViewController.h' file not found

### ISSUE THREAD

**Issue by Saqib92** [j3k0/cordova-plugin-openwith#118]
I am using this plugin on Capacitor 3.
1): After installation it is showing `'ShareViewController.h' file not found`. (Works fine on android).

2): To make it work on capacitor i installed it from `npm`. so i didn't have `--variables` set for this. Now what exactly i have to add into `info.plist` file to make it work. I am only want to receive `text/URLs` in my app. can any one share `info.plist` settings.

**Comment by oscar-gardiazabal** [comment]
Same error here with cordova

**Comment by Saqib92** [comment]
Was not able to resolve this issue. had to use Other Plugins. 
https://github.com/carsten-klaffke/send-intent
