### ISSUE TITLE
cant get text

### ISSUE THREAD

**Issue by alextapia007** [j3k0/cordova-plugin-openwith#120]
After include mimetype text, try to share chrome url, but items comes null

**Comment by AnouarMc** [comment]
Did you by any chance find a solution to this?

**Comment by alextapia007** [comment]
> Did you by any chance find a solution to this?

on Android try
https://github.com/j3k0/cordova-plugin-openwith/issues/27#issuecomment-1219905212

**Comment by AnouarMc** [comment]
Thanks for the quick response.
I ended up using a fork of this repo [https://github.com/missive/cordova-plugin-openwith](url)
which works out of the box
