### ISSUE TITLE
Base64 data seems to be different for the same file between IOS and Android

### ISSUE THREAD

**Issue by swamywiz** [j3k0/cordova-plugin-openwith#14]
What I notice is that on android the base64 data length is larger than one with IOS for the same file. Also for android data base64decode fails while it looks fine on IOS. Is there any difference on the base64 generation logic between the two or am I missing something?

**Comment by swamywiz** [comment]
had to change Base64.encodeToString(bytes, Base64.DEFAULT) to Base64.encodeToString(bytes, Base64.NOWRAP); in my case otherwise server side decode was failing.

**Comment by j3k0** [comment]
Thanks. I fixed this with 29ea3b2f1ed9fbfff705774a19c33be683a43982
