### ISSUE TITLE
PDF/XML not working

### ISSUE THREAD

**Issue by samianc** [j3k0/cordova-plugin-openwith#15]
I have been trying to configure the plugin with **public.content** in the **IOS_UNIFORM_TYPE_IDENTIFIER** variable, but it doesn't work. But **public.image** works. Why???

**Comment by j3k0** [comment]
The plugin has really only been tested with images, other file types might work but probably require some additional work within the plugin, especially for iOS which requires a specific view in the "Share" extension.

I'm available for hire if you wouldn't know how to start.
