### ISSUE TITLE
Open choose people dialog

### ISSUE THREAD

**Issue by iverveinc** [j3k0/cordova-plugin-openwith#17]
Hey,

First Of All, Thanks for the great plugin.

I want a functionality like, WhatsApp. I mean I want to share image with particular people on my App.  Is there any way I can open my custom page after I choose images and click on our app from Share? I can list out friends there and provide select option. 

Thanks :)

**Comment by j3k0** [comment]
Hey,

Sure, nothing will prevent you from doing custom anything with the image from within your app.
