### ISSUE TITLE
Data Base64 Error

### ISSUE THREAD

**Issue by ekambarrao** [j3k0/cordova-plugin-openwith#2]
Hi j3k0, Your plugin is awesome. it is working perfect until the point it reads the data of a image jpeg file. I rendered it to image src with prefixing standard jpeg file text. It is perfectly displaying in the page. now the problem starts from here, When I try to read the same image src back into javascript, it is quitting. Do I have to do something extra? thnq

**Comment by j3k0** [comment]
Old issue, please reopen if it is still valid... Or share your experience if it can be interesting.
