### ISSUE TITLE
Ionic 2 / 3 support?

### ISSUE THREAD

**Issue by tverilytt** [j3k0/cordova-plugin-openwith#21]
Hi!
I am using this plugin with Ionic v1 app. Now I am in process of upgrading app to Ionic 3. Will the plugin work there?
I found the Ionic Native Web Intent plugin, but it only supports Android...
https://ionicframework.com/docs/native/web-intent/

Cheers
-jo

**Comment by tverilytt** [comment]
Followed the steps in this article and works well:
https://www.joshmorony.com/using-cordova-plugins-in-ionic-2-with-ionic-native/

**Comment by UDTDR** [comment]
> Followed the steps in this article and works well:
> https://www.joshmorony.com/using-cordova-plugins-in-ionic-2-with-ionic-native/

Could you share your code please? Thanks

**Comment by tverilytt** [comment]
> > Followed the steps in this article and works well:
> > https://www.joshmorony.com/using-cordova-plugins-in-ionic-2-with-ionic-native/
> 
> Could you share your code please? Thanks

Sure, I havent look at the code for a while, what specifically are you looking for?

**Comment by fabianKut90** [comment]
Hi @tverilytt! I would also be interested how you made this work with ionic. I used ionic4 and my app already appears in the "open with" apps list of android. But I don't know how and where to include code so that I can read out the URL of the browser. thanks for helping!

**Comment by tverilytt** [comment]
Hi!

Below are the main content. I think the declare of cordova was the main thing that got things going...

---
ionic cordova plugin add https://github.com/j3k0/cordova-plugin-openwith.git \
  --variable ANDROID_MIME_TYPE="image/*" \
  --variable IOS_URL_SCHEME=ccfoveaopenwithdemo \
  --variable IOS_UNIFORM_TYPE_IDENTIFIER=public.image


---

declare var cordova;


cordova.openwith.init(initSuccess, initError);

cordova.openwith.addHandler(openwithHandler);

function initSuccess()  { console.log('openwith init success!'); }
function initError(err) { console.log('openwith init failed: ', err); }

function openwithHandler(intent) {
  if (intent.items.length > 0) {
     var item = intent.items[0];

     cordova.openwith.load(item,
       function(data, dataDescriptor) {
         console.log('openwithHandler openWith.load success, dataDescriptor', dataDescriptor);
       },
       function(error, dataDescriptor) {
         console.log('openWwth.load error ', error);
     });
  }
}
