### ISSUE TITLE
error: unexpected element <uses-permission> found in <manifest><application><activity>

### ISSUE THREAD

**Issue by merbin2012** [j3k0/cordova-plugin-openwith#22]
After adding this plugin I got the following error
error: unexpected element <uses-permission> found in <manifest><application><activity>.

![screenshot-github com-2018 07 08-15-37-00](https://user-images.githubusercontent.com/3687184/42418772-db314a36-82c4-11e8-8e0e-9f9c70e6b9e6.png)

**Comment by Gamerakki** [comment]
Even i am facing the same issue..anybody know how to resolve this..
cordova-android:7.1.0 and cordova version 8.0.0 i s be used

**Comment by j3k0** [comment]
PR #3 fixed this but wasn't released yet. I now released version `1.1.1` which includes the fix.
