### ISSUE TITLE
ios share doesn't work after  testflight

### ISSUE THREAD

**Issue by sotos89** [j3k0/cordova-plugin-openwith#48]
After installing the plugin, everything works perfect with sharing data in ios while running the app in my phone (choose a photo for share, and then open a specific view on my app for upload form).  But when i uploaded the app using testFlight the when i am using sharing to upload photos on my app, it opens the app bun doesn't have the same behaviour as running from xcode.

any idea what is going wrong?

**Comment by NiklasMerz** [comment]
Please check your production signing for the app extension in Xcode. Also check iOS device console in Xcode.

**Comment by sotos89** [comment]
hello,
The first scenario is, I have a bundle App Id E.g (com.my.app) and another App id for share extension E.g (com.my.app.shareextension) in booth App id I have enabled and assigned App Groups which is (group.com.my.app.shareextension) after deployed in TestFlight doesn't work.

The second scenario is a bundle App Id E.g (com.my.app) and another App id for share extension E.g (com.my.app.ShareExt) in booth App id I have enabled and assigned App Groups which is (group.com.my.app.shareextension) in booth cases it works while using xcode and running on my device but after deploying using TestFlight it doesn't work. 

I have tried also and automatically signing but the same result. 

any suggestion?

**Comment by NiklasMerz** [comment]
Did you check the device console? My last issue like that was related to using Xcode beta to upload and building for a newer platform.

**Comment by AlexanderHieser** [comment]
Hi,
maybe this is an issue with your entitlements.plist files. 
Inside your platform folder you can find two files for the Entitlements, one for debug and one for production builds. For some reason the plist file for your production builds ( which I assume is necessary for uploading your app to TestFlight) is not updated with the Capapilities you select in XCode. Have a look at the content of the release file and change it so it has the same content as the one for you debug builds ( which is working fine for you it seems)

**Comment by sotos89** [comment]
hello,
thank you for your response.
In my platform folder there are two file, in debug is something like: 
`<plist version="1.0">
<dict>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>group.com.my.app.shareextension</string>
	</array>
</dict>
</plist>`

but in production it's empty 
`<plist version="1.0">
    <dict>
    </dict>
</plist>`

so it should be the same. I will try to build and upload my app using the debug code to production plist file and I inform you about the result.

**Comment by sotos89** [comment]
hello 
After the @AlexanderHieser answer, the problem was solved.
thank you both for your help and quick response!
