### ISSUE TITLE
JSON serialization of intent returns null

### ISSUE THREAD

**Issue by nmatpt** [j3k0/cordova-plugin-openwith#5]
I have a Ionic app with this plugin that I am testing on an Android emulator. The plugin is initialized successfully but the handle function is never called. I added some logs and it seems that both `intent.getClipData` and `intent.getExtras` return null, which means that the `toJSONObject` returns null therefore intent is never processed.

I am testing this on an Android emulator 7.1.1 and I am opening a simple image from my Downloads folder. Here are some logs (I added the `intent.toString()`), let me know what else can I do to help with the troubleshooting:

```
D openwith: [native] onNewIntent() android.intent.action.VIEW
D openwith: [native] Intent { act=android.intent.action.VIEW dat=content://com.android.providers.downloads.documents/document/28 typ=image/jpeg flg=0x13000003 cmp=io.ionic.starter/.MainActivity }
D openwith: [native] processPendingIntents()
```

**Comment by j3k0** [comment]
Sorry for delay, wasn't able to handle support for a while. Did you get it to work?

**Comment by nmatpt** [comment]
Not really, I ended up doing things in a more "manual" way with another plugin
