### ISSUE TITLE
Question: Where to add the function in an Ionic project

### ISSUE THREAD

**Issue by fabianKut90** [j3k0/cordova-plugin-openwith#61]
Hi guys! 

I am new to Cordova and Ionic and I would love to know to include the usage function into my Ionic project? I assumed I have to add it to app.component.ts file but I get all kind of errors if I do so. 
Would be awesome if someone could guide me a bit in the right direction. 

Thank you!

**Comment by fabianKut90** [comment]
Hi guys! 
I made it work to integrate the plugin and I can successfully print the intent to the console and set it to local storage. Great plugin! 

However, I am struggling to call an outside method from the inner actionHandler function (in this case a router method to redirect the user in case an intent is found). I am quite new to javascript and I am not sure how to achieve this, but understand that my current "this" implementation makes no sense (see below). 
Thanks so much for helping out! 

`document.addEventListener('deviceready', setupOpenwith, false);

function setupOpenwith() {

  // Increase verbosity if you need more logs
  //cordova.openwith.setVerbosity(cordova.openwith.DEBUG);

  // Initialize the plugin
  cordova.openwith.init(initSuccess, initError);

  function initSuccess()  { console.log('init success!'); }
  function initError(err) { console.log('init failed: ' + err); }

  // Define your file handler
  cordova.openwith.addHandler(myHandler);

  function myHandler(intent) {
    for (var i = 0; i < intent.items.length; ++i) {
      var item = intent.items[i];


    //this part works 
    localstorage.setitem('test', item.utis)
    //this part does not work 
    this.router.navigate[['/profile']];
    }
}`

**Comment by NiklasMerz** [comment]
This is not an issue but more a question thats why I am closing this. 

But I can try to help you. You define your Handler as a function. Functions in javascript change the meaning of `this`. Try to use an arrow function (research it a bit you will understand after some practice).

So lets change `function myHandler(intent) {` to `const myHandler = (intent) => {` That should work and lets you use the `this` as your class. 

I was confused with this while starting, too.

**Comment by fabianKut90** [comment]
Thank you @niklas. This was the trick, thanks for pointing this out!
