### ISSUE TITLE
iOS fails to pass image from gallery to app

### ISSUE THREAD

**Issue by joshoconnor89** [j3k0/cordova-plugin-openwith#64]
I spent 10 hours trying to figure out why ios wont pass the image to the app.  Android works fine.

After much research, turns out I need to add a `SHAREEXT_GROUP_IDENTIFIER` in `ShareViewController.h` as it was null.

PLEASE update your documentation to include this!  No where does it mention `SHAREEXT_GROUP_IDENTIFIER`, and without this, the plugin doesnt work on ios.  There is nothing worse than docs that dont fully detail whats needed.

Thanks

**Comment by NiklasMerz** [comment]
Are you talking about the install parameter? This is mentioned in [README](https://github.com/j3k0/cordova-plugin-openwith#installation). Does setting this work out for you? Feel free to open this again if necessary. Sorry for the delay. This plugin is maintained in free-time.
