### ISSUE TITLE
Patching of Xcode Project File does not work

### ISSUE THREAD

**Issue by BigJenson** [j3k0/cordova-plugin-openwith#7]
Hi,

after installing the Plugin, i got no additional Target in XCode (for the ShareExtension).
The Hooks seem to run, but the Target is not added into the projec.pbxproj File.
```Copying "cc.fovea.cordova.openwith/ShareExtension" to ios...
Adding target "cc.fovea.cordova.openwith/ShareExtension" to XCode project
  - Folder containing your iOS project: /Users/jensfischer/angularProjects/xxxx/platforms/ios/
    Parsing existing project at location: /Users/jensfischer/angularProjects/xxxx/platforms/ios/xxxxx.xcodeproj/project.pbxproj...
    ShareExtension group already exists.
Added ShareExtension to XCode project
```
(Replaced the projects's name with xxxx for this issue)

Any ideas what could cause this?

**Comment by j3k0** [comment]
Hi. Got this to work? If so, how?

**Comment by NilLlisterri** [comment]
Hi! I'm trying to use the plugin on IOS.

I'm installing it with `ionic cordova plugin add git+https://github.com/j3k0/cordova-plugin-openwith#8dfcbfc --variable IOS_URL_SCHEME=myscheme --variable ANDROID_MIME_TYPE="*/*" --variable IOS_UNIFORM_TYPE_IDENTIFIER=public.image` (v1.2.0).

After a successfull installation with the same messages as the one in this thread (ShareExtension group already exists) if I try build the IOS platform the build fails with thise message:

`CompileC /Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/Objects-normal/armv7/OpenWithPlugin.o ProjectName/Plugins/cc.fovea.cordova.openwith/OpenWithPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/usr/Desktop/app/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/usr/Desktop/app/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/usr/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/usr/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCOCOAPODS=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=9.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -iquote /Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/ProjectName-generated-files.hmap -I/Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/ProjectName-own-target-headers.hmap -I/Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/ProjectName-all-target-headers.hmap -iquote /Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/ProjectName-project-headers.hmap -I/Users/usr/Desktop/app/platforms/ios/build/device/include -I/Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/InstallationBuildProductsLocation/Applications/usr/local/lib/include -I/Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/UninstalledProducts/include -I/Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/include -I/Users/usr/Desktop/app/platforms/ios/build/device -I/Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public -I/Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public/AccountKit -I/Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public/GGLInstanceID -I/Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public/GoogleCloudMessaging -I/Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/DerivedSources/armv7 -I/Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/DerivedSources -F/Users/usr/Desktop/app/platforms/ios/build/device -F/Users/usr/Desktop/app/platforms/ios/Pods/AccountKit -F/Users/usr/Desktop/app/platforms/ios/Pods/GoogleIPhoneUtilities/Frameworks -F/Users/usr/Desktop/app/platforms/ios/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/Users/usr/Desktop/app/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/Users/usr/Desktop/app/platforms/ios/Pods/GoogleUtilities/Frameworks/frameworks -isystem /Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public -isystem /Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public/AccountKit -isystem /Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public/GGLInstanceID -isystem /Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public/GoogleCloudMessaging -isystem /Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public -isystem /Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public/AccountKit -isystem /Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public/GGLInstanceID -isystem /Users/usr/Desktop/app/platforms/ios/Pods/Headers/Public/GoogleCloudMessaging -include /Users/usr/Desktop/app/platforms/ios/build/sharedpch/ProjectName-Prefix-dknmnvxctbhthkdkkhzgfqlmksge/ProjectName-Prefix.pch -MMD -MT dependencies -MF /Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/Objects-normal/armv7/OpenWithPlugin.d --serialize-diagnostics /Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/Objects-normal/armv7/OpenWithPlugin.dia -c /Users/usr/Desktop/app/platforms/ios/ProjectName/Plugins/cc.fovea.cordova.openwith/OpenWithPlugin.m -o /Users/usr/Library/Developer/Xcode/DerivedData/ProjectName-ejqvjzdmkxciwhcwumnaminysril/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Release-iphoneos/ProjectName.build/Objects-normal/armv7/OpenWithPlugin.o
/Users/usr/Desktop/app/platforms/ios/ProjectName/Plugins/cc.fovea.cordova.openwith/OpenWithPlugin.m:2:9: fatal error: 'ShareViewController.h' file not found
#import "ShareViewController.h"
        ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.`

To fix it, i copied the `ShareViewController.h` file to the IOS plugin folder (`platforms/ios/ProjectName/Plugins/cc.fovea.cordova.openwith`). I hope that's the right fix, because the build process now works.

Then, I'm getting the same behaviour as the OP. No errors but when I open the project with XCode there is no additional Target for the ShareExtension.

I'm using cordova-ios 4.5.5, and ionic 3.

Should I open a new issue?

Thanks!

**Comment by NilLlisterri** [comment]
For anyone facing the same problem: I had the same issue, but adding first the platform and then the plugin fixed it for me.
