### ISSUE TITLE
iOS app is not started

### ISSUE THREAD

**Issue by JanST123** [j3k0/cordova-plugin-openwith#8]
Hi, First i want to thank you for the plugin. On ios, when I share an Image to my app, and the app is not running, it will not start the app. The intent is then received when I start the app manually. If the app IS already running and I share, the app does not come to the foreground and the intent is received when I switch to the app.

Any idea what is wrong? 
Jan

**Comment by AlexanderHieser** [comment]
Hi,
do you have the correct IOS_URL_SCHEME defined? You can have a look at the ShareViewController.h to se if its correctly setup.

**Comment by NiklasMerz** [comment]
I am closing this issue. If it is still relevant with the current version please open a new one with up-to-date information. See also #67
