### ISSUE TITLE
unknown element <uses-permission>

### ISSUE THREAD

**Issue by madc0w** [j3k0/cordova-plugin-openwith#9]
While attempting to build with this plugin:

.meteor/local/cordova-build/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:113:
   AAPT: error: unknown element <uses-permission> found.

**Comment by madc0w** [comment]
Here is what I see in AndroidManifest.xml:

```
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="17583452" android:versionName="1.2" package="com.spoti
cle" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizea
ble="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android
:supportsRtl="true">

```

and according to https://github.com/priteshrnandgaonkar/react-native-call-detection/issues/6 , this uses-permissions tag is actually precisely where it needs to be.

**Comment by madc0w** [comment]
Here is what I see in AndroidManifest.xml line 113:

```
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

According to https://github.com/priteshrnandgaonkar/react-native-call-detection/issues/6 , this uses-permissions tag needs to be directly under <manifest>.

**Comment by j3k0** [comment]
Thanks. Seems like this permission wasn't so much needed (I think it was for getting sharing work for files from external storage, but not 100% sure now).

**Comment by madc0w** [comment]
Thanks, but I'm still having the same issue.
In what version was this fix released?  It seems like the current version number has not changed, still 1.1.0.

**Comment by compelling** [comment]
Having this issue too. Removed uses-permission in plugin.and and added this:
       
<config-file target="AndroidManifest.xml" parent="/manifest">
           <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
</config-file>

**Comment by merbin2012** [comment]
@compelling I didn't get you, can you please give me more details?

**Comment by tverilytt** [comment]
I just commented out the line in plugin.xml:
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

**Comment by merbin2012** [comment]
@tverilytt When I build it, it resets.

**Comment by tverilytt** [comment]
@merbin2012 Yes, I had to do a platform rm and add again, e.g. for android.

**Comment by merbin2012** [comment]
@tverilytt Is this plugin work for other formats? For me, only image files are working.
